### ISSUE TITLE
Width & dropdown menu issue when using Bootstrap

### ISSUE THREAD

**Issue by pplomteux** [adamjimenez/jstree-grid#27]
Hello,
I posted the following [jsfiddle](http://jsfiddle.net/plemdoux/p5jrw40w/) that highlights two issues I am having with jstreetable : 
1. Column width not taken into account - there may be a conflict with bootstrap style sheets but I have not been able to identify it
2. I cannot make a bootstrap drop-down menu to open when provided as html in a jstreetable colon.
Thank you !

**Comment by pplomteux** [comment]
Issue #2 in my first post can be fixed using styling of the context menu, will post a solution when I have addressed it.
Issue #1 above still remains.

**Comment by dorel14** [comment]
Hello , i thonk i have the same problem with bootstrap, can you send me some code of how you resolve your problem ?

Thx
